on:
  push:
    branches:
      - main
      
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:      
      - name: 🎉 Create release info
        uses: google-github-actions/release-please-action@v3
        id: releaseplease
        with:
          release-type: expo
          
